"""Neutral LLM gateway.

This package knows about providers, not about products. It never imports a
consuming application, never reads credentials on import and never logs prompt
or response content by default.
"""

from llm_gateway.audio import (
    AudioAttempt,
    AudioExecution,
    AudioInput,
    AudioSegment,
    ProviderTranscriptionResponse,
    TranscriptionRequest,
    TranscriptionResult,
)
from llm_gateway.capabilities import ProviderCapabilities
from llm_gateway.contracts import (
    Attempt,
    AttemptOutcome,
    Execution,
    FailurePhase,
    FileAttachment,
    LLMRequest,
    LLMResult,
    Message,
    ReasoningEffort,
    ResponseFormat,
    Role,
)
from llm_gateway.errors import (
    AllAttemptsFailed,
    AllTranscriptionsFailed,
    AuthenticationError,
    ConfigurationError,
    InvalidRequestError,
    LLMGatewayError,
    OutputError,
    OutputParsingError,
    ProviderError,
    ProviderNotInstalled,
    ProviderTimeoutError,
    RateLimitedError,
    SchemaValidationError,
    ServiceUnavailableError,
    UnknownModelError,
)
from llm_gateway.gateway import LLMGateway
from llm_gateway.models import (
    CATALOG_VERSION,
    MODEL_CATALOG,
    ModelInfo,
    builtin_audio_price_catalog,
    builtin_price_catalog,
    lookup_model,
    models_by_provider,
    resolve_provider,
)
from llm_gateway.policies import FallbackPolicy, RetryPolicy, TimeoutPolicy
from llm_gateway.ports import (
    AlertSink,
    AudioUsageRecord,
    AudioUsageSink,
    EventSink,
    NullAlertSink,
    NullAudioUsageSink,
    NullEventSink,
    NullUsageSink,
    UsageRecord,
    UsageSink,
)
from llm_gateway.pricing import (
    AudioCost,
    AudioPriceCatalog,
    AudioRate,
    Cost,
    CostMeasurement,
    ModelRate,
    NullPriceCatalog,
    PriceCatalog,
    StaticAudioPriceCatalog,
    StaticPriceCatalog,
)
from llm_gateway.providers.base import (
    AudioProviderAdapter,
    ProviderAdapter,
    ProviderResponse,
)
from llm_gateway.registry import ProviderRegistry
from llm_gateway.usage import AudioUsage, TokenUsage

__all__ = [
    "CATALOG_VERSION",
    "MODEL_CATALOG",
    "AlertSink",
    "AllAttemptsFailed",
    "AllTranscriptionsFailed",
    "Attempt",
    "AttemptOutcome",
    "AudioAttempt",
    "AudioCost",
    "AudioExecution",
    "AudioInput",
    "AudioPriceCatalog",
    "AudioProviderAdapter",
    "AudioRate",
    "AudioSegment",
    "AudioUsage",
    "AudioUsageRecord",
    "AudioUsageSink",
    "AuthenticationError",
    "ConfigurationError",
    "Cost",
    "CostMeasurement",
    "EventSink",
    "Execution",
    "FailurePhase",
    "FallbackPolicy",
    "FileAttachment",
    "InvalidRequestError",
    "LLMGateway",
    "LLMGatewayError",
    "LLMRequest",
    "LLMResult",
    "Message",
    "ModelInfo",
    "ModelRate",
    "NullAlertSink",
    "NullAudioUsageSink",
    "NullEventSink",
    "NullPriceCatalog",
    "NullUsageSink",
    "OutputError",
    "OutputParsingError",
    "PriceCatalog",
    "ProviderAdapter",
    "ProviderCapabilities",
    "ProviderError",
    "ProviderNotInstalled",
    "ProviderRegistry",
    "ProviderResponse",
    "ProviderTimeoutError",
    "ProviderTranscriptionResponse",
    "RateLimitedError",
    "ReasoningEffort",
    "ResponseFormat",
    "RetryPolicy",
    "Role",
    "SchemaValidationError",
    "ServiceUnavailableError",
    "StaticAudioPriceCatalog",
    "StaticPriceCatalog",
    "TimeoutPolicy",
    "TokenUsage",
    "TranscriptionRequest",
    "TranscriptionResult",
    "UnknownModelError",
    "UsageRecord",
    "UsageSink",
    "builtin_audio_price_catalog",
    "builtin_price_catalog",
    "lookup_model",
    "models_by_provider",
    "resolve_provider",
]
